### ISSUE TITLE
MCP not converged

### ISSUE THREAD

**Issue by FM-He** [xinjie-liu/DifferentiableAdaptiveGames.jl#1]
Hi Xinjie,

I've recently taken an interest in your project and attempted to run the code as per the documentation. However, I've encountered some issues when executing the DrivingExample.ramp_merging_inference() function.

Here's a detailed breakdown of the problem:

julia> DrivingExample.ramp_merging_inference()
Sampling initial states and goals...
#########################
 New Iteration: 1/1
#########################
┌ Warning: MCP not converged: PATH solver status is MCP_OK.
└ @ ParametricMCPs ~/.julia/packages/ParametricMCPs/q8NCN/src/solver.jl:46
┌ Warning: MCP not converged: PATH solver status is MCP_OK.
└ @ ParametricMCPs ~/.julia/packages/ParametricMCPs/q8NCN/src/solver.jl:46
[ Info: Solve failed, re-initializing...
┌ Warning: MCP not converged: PATH solver status is MCP_OK.
└ @ ParametricMCPs ~/.julia/packages/ParametricMCPs/q8NCN/src/solver.jl:46
ERROR: **ArgumentError: This strategy is only valid for states on its trajectory but has been called for an off trajectory state instead which will likely not produce meaningful results.**

**Comment by xinjie-liu** [comment]
Hi there,

Thanks for bringing that up. I just ran the script on my machine and it worked for me. I think the problem here is that the problem size is larger than PATHSolver allows to solve without a license. Could you try to get a license for the PATHSolver (free) as instructed [here](https://github.com/chkwon/PATHSolver.jl) in the "License" section and run it again?

**Comment by lassepe** [comment]
This will indeed be a license issue. If the license is not set, PATH just returns `NaN` as a solution (which, when compared to the intiial state) will trigger the argument error quoted above. 

We have recently added a license check to PATHSolver.jl to make this error more informative.
https://github.com/chkwon/PATHSolver.jl/releases


I will close this issue. @FM-He , should you still see this error with a license (and after updating to PATHSolver 1.7.1), please feel free to re-open.
