### ISSUE TITLE
I got this

### ISSUE THREAD

**Issue by TianleLiu0303** [xinjie-liu/DifferentiableAdaptiveGames.jl#2]
Warning: MCP not converged: PATH solver status is MCP_OK.
└ @ ParametricMCPs ~/.julia/packages/ParametricMCPs/KdzCk/src/solver.jl:46
ERROR: ArgumentError: This strategy is only valid for states on its trajectory but has been called for an off trajectory state instead which will likely not produce meaningful results.

**Comment by xinjie-liu** [comment]
Hi there, it looks like the license for PATH Solver is not set up properly. You can get a free license from [here](https://github.com/chkwon/PATHSolver.jl) (the License section) and try again.

**Comment by TianleLiu0303** [comment]
Thanks for your reply,I  have solved the  problem!!
